/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-07-04 at 07:53:39 UTC 
 * Modify at your own risk.
 */

package com.sp.fanikiwa.entity.loanendpoint;

/**
 * Service definition for Loanendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link LoanendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Loanendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the loanendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://1-dot-fanikiwaweb.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "loanendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Loanendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Loanendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "editLoan".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link EditLoan#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.sp.fanikiwa.entity.loanendpoint.model.LoanDTO}
   * @return the request
   */
  public EditLoan editLoan(com.sp.fanikiwa.entity.loanendpoint.model.LoanDTO content) throws java.io.IOException {
    EditLoan result = new EditLoan(content);
    initialize(result);
    return result;
  }

  public class EditLoan extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.RequestResult> {

    private static final String REST_PATH = "editLoan";

    /**
     * Create a request for the method "editLoan".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link EditLoan#execute()} method to invoke the remote operation.
     * <p> {@link
     * EditLoan#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.sp.fanikiwa.entity.loanendpoint.model.LoanDTO}
     * @since 1.13
     */
    protected EditLoan(com.sp.fanikiwa.entity.loanendpoint.model.LoanDTO content) {
      super(Loanendpoint.this, "POST", REST_PATH, content, com.sp.fanikiwa.entity.loanendpoint.model.RequestResult.class);
    }

    @Override
    public EditLoan setAlt(java.lang.String alt) {
      return (EditLoan) super.setAlt(alt);
    }

    @Override
    public EditLoan setFields(java.lang.String fields) {
      return (EditLoan) super.setFields(fields);
    }

    @Override
    public EditLoan setKey(java.lang.String key) {
      return (EditLoan) super.setKey(key);
    }

    @Override
    public EditLoan setOauthToken(java.lang.String oauthToken) {
      return (EditLoan) super.setOauthToken(oauthToken);
    }

    @Override
    public EditLoan setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EditLoan) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EditLoan setQuotaUser(java.lang.String quotaUser) {
      return (EditLoan) super.setQuotaUser(quotaUser);
    }

    @Override
    public EditLoan setUserIp(java.lang.String userIp) {
      return (EditLoan) super.setUserIp(userIp);
    }

    @Override
    public EditLoan set(String parameterName, Object value) {
      return (EditLoan) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getLoanByID".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link GetLoanByID#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetLoanByID getLoanByID(java.lang.Long id) throws java.io.IOException {
    GetLoanByID result = new GetLoanByID(id);
    initialize(result);
    return result;
  }

  public class GetLoanByID extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.Loan> {

    private static final String REST_PATH = "loan/{id}";

    /**
     * Create a request for the method "getLoanByID".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link GetLoanByID#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetLoanByID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetLoanByID(java.lang.Long id) {
      super(Loanendpoint.this, "GET", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.Loan.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetLoanByID setAlt(java.lang.String alt) {
      return (GetLoanByID) super.setAlt(alt);
    }

    @Override
    public GetLoanByID setFields(java.lang.String fields) {
      return (GetLoanByID) super.setFields(fields);
    }

    @Override
    public GetLoanByID setKey(java.lang.String key) {
      return (GetLoanByID) super.setKey(key);
    }

    @Override
    public GetLoanByID setOauthToken(java.lang.String oauthToken) {
      return (GetLoanByID) super.setOauthToken(oauthToken);
    }

    @Override
    public GetLoanByID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetLoanByID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetLoanByID setQuotaUser(java.lang.String quotaUser) {
      return (GetLoanByID) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetLoanByID setUserIp(java.lang.String userIp) {
      return (GetLoanByID) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetLoanByID setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetLoanByID set(String parameterName, Object value) {
      return (GetLoanByID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertLoan".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link InsertLoan#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.sp.fanikiwa.entity.loanendpoint.model.Loan}
   * @return the request
   */
  public InsertLoan insertLoan(com.sp.fanikiwa.entity.loanendpoint.model.Loan content) throws java.io.IOException {
    InsertLoan result = new InsertLoan(content);
    initialize(result);
    return result;
  }

  public class InsertLoan extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.Loan> {

    private static final String REST_PATH = "loan";

    /**
     * Create a request for the method "insertLoan".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link InsertLoan#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertLoan#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.sp.fanikiwa.entity.loanendpoint.model.Loan}
     * @since 1.13
     */
    protected InsertLoan(com.sp.fanikiwa.entity.loanendpoint.model.Loan content) {
      super(Loanendpoint.this, "POST", REST_PATH, content, com.sp.fanikiwa.entity.loanendpoint.model.Loan.class);
    }

    @Override
    public InsertLoan setAlt(java.lang.String alt) {
      return (InsertLoan) super.setAlt(alt);
    }

    @Override
    public InsertLoan setFields(java.lang.String fields) {
      return (InsertLoan) super.setFields(fields);
    }

    @Override
    public InsertLoan setKey(java.lang.String key) {
      return (InsertLoan) super.setKey(key);
    }

    @Override
    public InsertLoan setOauthToken(java.lang.String oauthToken) {
      return (InsertLoan) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertLoan setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertLoan) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertLoan setQuotaUser(java.lang.String quotaUser) {
      return (InsertLoan) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertLoan setUserIp(java.lang.String userIp) {
      return (InsertLoan) super.setUserIp(userIp);
    }

    @Override
    public InsertLoan set(String parameterName, Object value) {
      return (InsertLoan) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listLoan".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link ListLoan#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListLoan listLoan() throws java.io.IOException {
    ListLoan result = new ListLoan();
    initialize(result);
    return result;
  }

  public class ListLoan extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoan> {

    private static final String REST_PATH = "loan";

    /**
     * Create a request for the method "listLoan".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link ListLoan#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListLoan#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListLoan() {
      super(Loanendpoint.this, "GET", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoan.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListLoan setAlt(java.lang.String alt) {
      return (ListLoan) super.setAlt(alt);
    }

    @Override
    public ListLoan setFields(java.lang.String fields) {
      return (ListLoan) super.setFields(fields);
    }

    @Override
    public ListLoan setKey(java.lang.String key) {
      return (ListLoan) super.setKey(key);
    }

    @Override
    public ListLoan setOauthToken(java.lang.String oauthToken) {
      return (ListLoan) super.setOauthToken(oauthToken);
    }

    @Override
    public ListLoan setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListLoan) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListLoan setQuotaUser(java.lang.String quotaUser) {
      return (ListLoan) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListLoan setUserIp(java.lang.String userIp) {
      return (ListLoan) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public ListLoan setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListLoan setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public ListLoan set(String parameterName, Object value) {
      return (ListLoan) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "loanRepaymentSchedule".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link LoanRepaymentSchedule#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public LoanRepaymentSchedule loanRepaymentSchedule(java.lang.Long id) throws java.io.IOException {
    LoanRepaymentSchedule result = new LoanRepaymentSchedule(id);
    initialize(result);
    return result;
  }

  public class LoanRepaymentSchedule extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.RequestResult> {

    private static final String REST_PATH = "LoanRepaymentSchedule/{id}";

    /**
     * Create a request for the method "loanRepaymentSchedule".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link LoanRepaymentSchedule#execute()} method to invoke the
     * remote operation. <p> {@link LoanRepaymentSchedule#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected LoanRepaymentSchedule(java.lang.Long id) {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.RequestResult.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public LoanRepaymentSchedule setAlt(java.lang.String alt) {
      return (LoanRepaymentSchedule) super.setAlt(alt);
    }

    @Override
    public LoanRepaymentSchedule setFields(java.lang.String fields) {
      return (LoanRepaymentSchedule) super.setFields(fields);
    }

    @Override
    public LoanRepaymentSchedule setKey(java.lang.String key) {
      return (LoanRepaymentSchedule) super.setKey(key);
    }

    @Override
    public LoanRepaymentSchedule setOauthToken(java.lang.String oauthToken) {
      return (LoanRepaymentSchedule) super.setOauthToken(oauthToken);
    }

    @Override
    public LoanRepaymentSchedule setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (LoanRepaymentSchedule) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public LoanRepaymentSchedule setQuotaUser(java.lang.String quotaUser) {
      return (LoanRepaymentSchedule) super.setQuotaUser(quotaUser);
    }

    @Override
    public LoanRepaymentSchedule setUserIp(java.lang.String userIp) {
      return (LoanRepaymentSchedule) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public LoanRepaymentSchedule setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public LoanRepaymentSchedule setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public LoanRepaymentSchedule setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public LoanRepaymentSchedule set(String parameterName, Object value) {
      return (LoanRepaymentSchedule) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "nextIntAccrualLoanByDate".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link NextIntAccrualLoanByDate#execute()} method to invoke the remote
   * operation.
   *
   * @param date
   * @return the request
   */
  public NextIntAccrualLoanByDate nextIntAccrualLoanByDate(com.google.api.client.util.DateTime date) throws java.io.IOException {
    NextIntAccrualLoanByDate result = new NextIntAccrualLoanByDate(date);
    initialize(result);
    return result;
  }

  public class NextIntAccrualLoanByDate extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoan> {

    private static final String REST_PATH = "NextIntAccrualLoanByDate/{date}";

    /**
     * Create a request for the method "nextIntAccrualLoanByDate".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link NextIntAccrualLoanByDate#execute()} method to invoke the
     * remote operation. <p> {@link NextIntAccrualLoanByDate#initialize(com.google.api.client.googleap
     * is.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param date
     * @since 1.13
     */
    protected NextIntAccrualLoanByDate(com.google.api.client.util.DateTime date) {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoan.class);
      this.date = com.google.api.client.util.Preconditions.checkNotNull(date, "Required parameter date must be specified.");
    }

    @Override
    public NextIntAccrualLoanByDate setAlt(java.lang.String alt) {
      return (NextIntAccrualLoanByDate) super.setAlt(alt);
    }

    @Override
    public NextIntAccrualLoanByDate setFields(java.lang.String fields) {
      return (NextIntAccrualLoanByDate) super.setFields(fields);
    }

    @Override
    public NextIntAccrualLoanByDate setKey(java.lang.String key) {
      return (NextIntAccrualLoanByDate) super.setKey(key);
    }

    @Override
    public NextIntAccrualLoanByDate setOauthToken(java.lang.String oauthToken) {
      return (NextIntAccrualLoanByDate) super.setOauthToken(oauthToken);
    }

    @Override
    public NextIntAccrualLoanByDate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (NextIntAccrualLoanByDate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public NextIntAccrualLoanByDate setQuotaUser(java.lang.String quotaUser) {
      return (NextIntAccrualLoanByDate) super.setQuotaUser(quotaUser);
    }

    @Override
    public NextIntAccrualLoanByDate setUserIp(java.lang.String userIp) {
      return (NextIntAccrualLoanByDate) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime date;

    /**

     */
    public com.google.api.client.util.DateTime getDate() {
      return date;
    }

    public NextIntAccrualLoanByDate setDate(com.google.api.client.util.DateTime date) {
      this.date = date;
      return this;
    }

    @Override
    public NextIntAccrualLoanByDate set(String parameterName, Object value) {
      return (NextIntAccrualLoanByDate) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "nextIntAppLoanByDate".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link NextIntAppLoanByDate#execute()} method to invoke the remote
   * operation.
   *
   * @param date
   * @return the request
   */
  public NextIntAppLoanByDate nextIntAppLoanByDate(com.google.api.client.util.DateTime date) throws java.io.IOException {
    NextIntAppLoanByDate result = new NextIntAppLoanByDate(date);
    initialize(result);
    return result;
  }

  public class NextIntAppLoanByDate extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoan> {

    private static final String REST_PATH = "NextIntAppLoanByDate/{date}";

    /**
     * Create a request for the method "nextIntAppLoanByDate".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link NextIntAppLoanByDate#execute()} method to invoke the
     * remote operation. <p> {@link NextIntAppLoanByDate#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param date
     * @since 1.13
     */
    protected NextIntAppLoanByDate(com.google.api.client.util.DateTime date) {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoan.class);
      this.date = com.google.api.client.util.Preconditions.checkNotNull(date, "Required parameter date must be specified.");
    }

    @Override
    public NextIntAppLoanByDate setAlt(java.lang.String alt) {
      return (NextIntAppLoanByDate) super.setAlt(alt);
    }

    @Override
    public NextIntAppLoanByDate setFields(java.lang.String fields) {
      return (NextIntAppLoanByDate) super.setFields(fields);
    }

    @Override
    public NextIntAppLoanByDate setKey(java.lang.String key) {
      return (NextIntAppLoanByDate) super.setKey(key);
    }

    @Override
    public NextIntAppLoanByDate setOauthToken(java.lang.String oauthToken) {
      return (NextIntAppLoanByDate) super.setOauthToken(oauthToken);
    }

    @Override
    public NextIntAppLoanByDate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (NextIntAppLoanByDate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public NextIntAppLoanByDate setQuotaUser(java.lang.String quotaUser) {
      return (NextIntAppLoanByDate) super.setQuotaUser(quotaUser);
    }

    @Override
    public NextIntAppLoanByDate setUserIp(java.lang.String userIp) {
      return (NextIntAppLoanByDate) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime date;

    /**

     */
    public com.google.api.client.util.DateTime getDate() {
      return date;
    }

    public NextIntAppLoanByDate setDate(com.google.api.client.util.DateTime date) {
      this.date = date;
      return this;
    }

    @Override
    public NextIntAppLoanByDate set(String parameterName, Object value) {
      return (NextIntAppLoanByDate) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "prepayLoan".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link PrepayLoan#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param amount
   * @return the request
   */
  public PrepayLoan prepayLoan(java.lang.Long id, java.lang.Double amount) throws java.io.IOException {
    PrepayLoan result = new PrepayLoan(id, amount);
    initialize(result);
    return result;
  }

  public class PrepayLoan extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.RequestResult> {

    private static final String REST_PATH = "prepayLoan/{id}/{amount}";

    /**
     * Create a request for the method "prepayLoan".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link PrepayLoan#execute()} method to invoke the remote
     * operation. <p> {@link
     * PrepayLoan#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param amount
     * @since 1.13
     */
    protected PrepayLoan(java.lang.Long id, java.lang.Double amount) {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.RequestResult.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.amount = com.google.api.client.util.Preconditions.checkNotNull(amount, "Required parameter amount must be specified.");
    }

    @Override
    public PrepayLoan setAlt(java.lang.String alt) {
      return (PrepayLoan) super.setAlt(alt);
    }

    @Override
    public PrepayLoan setFields(java.lang.String fields) {
      return (PrepayLoan) super.setFields(fields);
    }

    @Override
    public PrepayLoan setKey(java.lang.String key) {
      return (PrepayLoan) super.setKey(key);
    }

    @Override
    public PrepayLoan setOauthToken(java.lang.String oauthToken) {
      return (PrepayLoan) super.setOauthToken(oauthToken);
    }

    @Override
    public PrepayLoan setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (PrepayLoan) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public PrepayLoan setQuotaUser(java.lang.String quotaUser) {
      return (PrepayLoan) super.setQuotaUser(quotaUser);
    }

    @Override
    public PrepayLoan setUserIp(java.lang.String userIp) {
      return (PrepayLoan) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public PrepayLoan setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double amount;

    /**

     */
    public java.lang.Double getAmount() {
      return amount;
    }

    public PrepayLoan setAmount(java.lang.Double amount) {
      this.amount = amount;
      return this;
    }

    @Override
    public PrepayLoan set(String parameterName, Object value) {
      return (PrepayLoan) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeLoan".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link RemoveLoan#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveLoan removeLoan(java.lang.Long id) throws java.io.IOException {
    RemoveLoan result = new RemoveLoan(id);
    initialize(result);
    return result;
  }

  public class RemoveLoan extends LoanendpointRequest<Void> {

    private static final String REST_PATH = "loan/{id}";

    /**
     * Create a request for the method "removeLoan".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link RemoveLoan#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveLoan#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveLoan(java.lang.Long id) {
      super(Loanendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveLoan setAlt(java.lang.String alt) {
      return (RemoveLoan) super.setAlt(alt);
    }

    @Override
    public RemoveLoan setFields(java.lang.String fields) {
      return (RemoveLoan) super.setFields(fields);
    }

    @Override
    public RemoveLoan setKey(java.lang.String key) {
      return (RemoveLoan) super.setKey(key);
    }

    @Override
    public RemoveLoan setOauthToken(java.lang.String oauthToken) {
      return (RemoveLoan) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveLoan setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveLoan) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveLoan setQuotaUser(java.lang.String quotaUser) {
      return (RemoveLoan) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveLoan setUserIp(java.lang.String userIp) {
      return (RemoveLoan) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveLoan setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveLoan set(String parameterName, Object value) {
      return (RemoveLoan) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "retrieveLoan".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link RetrieveLoan#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RetrieveLoan retrieveLoan(java.lang.Long id) throws java.io.IOException {
    RetrieveLoan result = new RetrieveLoan(id);
    initialize(result);
    return result;
  }

  public class RetrieveLoan extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.RequestResult> {

    private static final String REST_PATH = "retrieveLoan/{id}";

    /**
     * Create a request for the method "retrieveLoan".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link RetrieveLoan#execute()} method to invoke the remote
     * operation. <p> {@link
     * RetrieveLoan#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RetrieveLoan(java.lang.Long id) {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.RequestResult.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RetrieveLoan setAlt(java.lang.String alt) {
      return (RetrieveLoan) super.setAlt(alt);
    }

    @Override
    public RetrieveLoan setFields(java.lang.String fields) {
      return (RetrieveLoan) super.setFields(fields);
    }

    @Override
    public RetrieveLoan setKey(java.lang.String key) {
      return (RetrieveLoan) super.setKey(key);
    }

    @Override
    public RetrieveLoan setOauthToken(java.lang.String oauthToken) {
      return (RetrieveLoan) super.setOauthToken(oauthToken);
    }

    @Override
    public RetrieveLoan setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RetrieveLoan) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RetrieveLoan setQuotaUser(java.lang.String quotaUser) {
      return (RetrieveLoan) super.setQuotaUser(quotaUser);
    }

    @Override
    public RetrieveLoan setUserIp(java.lang.String userIp) {
      return (RetrieveLoan) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RetrieveLoan setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RetrieveLoan set(String parameterName, Object value) {
      return (RetrieveLoan) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "reverseMemberLoans".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link ReverseMemberLoans#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public ReverseMemberLoans reverseMemberLoans(java.lang.Long id) throws java.io.IOException {
    ReverseMemberLoans result = new ReverseMemberLoans(id);
    initialize(result);
    return result;
  }

  public class ReverseMemberLoans extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.RequestResult> {

    private static final String REST_PATH = "ReverseMemberLoans/{id}";

    /**
     * Create a request for the method "reverseMemberLoans".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link ReverseMemberLoans#execute()} method to invoke the remote
     * operation. <p> {@link ReverseMemberLoans#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected ReverseMemberLoans(java.lang.Long id) {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.RequestResult.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public ReverseMemberLoans setAlt(java.lang.String alt) {
      return (ReverseMemberLoans) super.setAlt(alt);
    }

    @Override
    public ReverseMemberLoans setFields(java.lang.String fields) {
      return (ReverseMemberLoans) super.setFields(fields);
    }

    @Override
    public ReverseMemberLoans setKey(java.lang.String key) {
      return (ReverseMemberLoans) super.setKey(key);
    }

    @Override
    public ReverseMemberLoans setOauthToken(java.lang.String oauthToken) {
      return (ReverseMemberLoans) super.setOauthToken(oauthToken);
    }

    @Override
    public ReverseMemberLoans setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ReverseMemberLoans) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ReverseMemberLoans setQuotaUser(java.lang.String quotaUser) {
      return (ReverseMemberLoans) super.setQuotaUser(quotaUser);
    }

    @Override
    public ReverseMemberLoans setUserIp(java.lang.String userIp) {
      return (ReverseMemberLoans) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public ReverseMemberLoans setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public ReverseMemberLoans set(String parameterName, Object value) {
      return (ReverseMemberLoans) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "selectDtoLoans".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link SelectDtoLoans#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public SelectDtoLoans selectDtoLoans() throws java.io.IOException {
    SelectDtoLoans result = new SelectDtoLoans();
    initialize(result);
    return result;
  }

  public class SelectDtoLoans extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoanDTO> {

    private static final String REST_PATH = "selectDtoLoans";

    /**
     * Create a request for the method "selectDtoLoans".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link SelectDtoLoans#execute()} method to invoke the remote
     * operation. <p> {@link SelectDtoLoans#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected SelectDtoLoans() {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoanDTO.class);
    }

    @Override
    public SelectDtoLoans setAlt(java.lang.String alt) {
      return (SelectDtoLoans) super.setAlt(alt);
    }

    @Override
    public SelectDtoLoans setFields(java.lang.String fields) {
      return (SelectDtoLoans) super.setFields(fields);
    }

    @Override
    public SelectDtoLoans setKey(java.lang.String key) {
      return (SelectDtoLoans) super.setKey(key);
    }

    @Override
    public SelectDtoLoans setOauthToken(java.lang.String oauthToken) {
      return (SelectDtoLoans) super.setOauthToken(oauthToken);
    }

    @Override
    public SelectDtoLoans setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SelectDtoLoans) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SelectDtoLoans setQuotaUser(java.lang.String quotaUser) {
      return (SelectDtoLoans) super.setQuotaUser(quotaUser);
    }

    @Override
    public SelectDtoLoans setUserIp(java.lang.String userIp) {
      return (SelectDtoLoans) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public SelectDtoLoans setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public SelectDtoLoans setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public SelectDtoLoans set(String parameterName, Object value) {
      return (SelectDtoLoans) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "selectDtoMyInvestments".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link SelectDtoMyInvestments#execute()} method to invoke the remote
   * operation.
   *
   * @param email
   * @return the request
   */
  public SelectDtoMyInvestments selectDtoMyInvestments(java.lang.String email) throws java.io.IOException {
    SelectDtoMyInvestments result = new SelectDtoMyInvestments(email);
    initialize(result);
    return result;
  }

  public class SelectDtoMyInvestments extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoanDTO> {

    private static final String REST_PATH = "selectDtoMyInvestments/{email}";

    /**
     * Create a request for the method "selectDtoMyInvestments".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link SelectDtoMyInvestments#execute()} method to invoke the
     * remote operation. <p> {@link SelectDtoMyInvestments#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param email
     * @since 1.13
     */
    protected SelectDtoMyInvestments(java.lang.String email) {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoanDTO.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public SelectDtoMyInvestments setAlt(java.lang.String alt) {
      return (SelectDtoMyInvestments) super.setAlt(alt);
    }

    @Override
    public SelectDtoMyInvestments setFields(java.lang.String fields) {
      return (SelectDtoMyInvestments) super.setFields(fields);
    }

    @Override
    public SelectDtoMyInvestments setKey(java.lang.String key) {
      return (SelectDtoMyInvestments) super.setKey(key);
    }

    @Override
    public SelectDtoMyInvestments setOauthToken(java.lang.String oauthToken) {
      return (SelectDtoMyInvestments) super.setOauthToken(oauthToken);
    }

    @Override
    public SelectDtoMyInvestments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SelectDtoMyInvestments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SelectDtoMyInvestments setQuotaUser(java.lang.String quotaUser) {
      return (SelectDtoMyInvestments) super.setQuotaUser(quotaUser);
    }

    @Override
    public SelectDtoMyInvestments setUserIp(java.lang.String userIp) {
      return (SelectDtoMyInvestments) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public SelectDtoMyInvestments setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public SelectDtoMyInvestments setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public SelectDtoMyInvestments setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public SelectDtoMyInvestments set(String parameterName, Object value) {
      return (SelectDtoMyInvestments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "selectDtoMyLoans".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link SelectDtoMyLoans#execute()} method to invoke the remote operation.
   *
   * @param email
   * @return the request
   */
  public SelectDtoMyLoans selectDtoMyLoans(java.lang.String email) throws java.io.IOException {
    SelectDtoMyLoans result = new SelectDtoMyLoans(email);
    initialize(result);
    return result;
  }

  public class SelectDtoMyLoans extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoanDTO> {

    private static final String REST_PATH = "selectDtoMyLoans/{email}";

    /**
     * Create a request for the method "selectDtoMyLoans".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link SelectDtoMyLoans#execute()} method to invoke the remote
     * operation. <p> {@link SelectDtoMyLoans#initialize(com.google.api.client.googleapis.services.Abs
     * tractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param email
     * @since 1.13
     */
    protected SelectDtoMyLoans(java.lang.String email) {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoanDTO.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public SelectDtoMyLoans setAlt(java.lang.String alt) {
      return (SelectDtoMyLoans) super.setAlt(alt);
    }

    @Override
    public SelectDtoMyLoans setFields(java.lang.String fields) {
      return (SelectDtoMyLoans) super.setFields(fields);
    }

    @Override
    public SelectDtoMyLoans setKey(java.lang.String key) {
      return (SelectDtoMyLoans) super.setKey(key);
    }

    @Override
    public SelectDtoMyLoans setOauthToken(java.lang.String oauthToken) {
      return (SelectDtoMyLoans) super.setOauthToken(oauthToken);
    }

    @Override
    public SelectDtoMyLoans setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SelectDtoMyLoans) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SelectDtoMyLoans setQuotaUser(java.lang.String quotaUser) {
      return (SelectDtoMyLoans) super.setQuotaUser(quotaUser);
    }

    @Override
    public SelectDtoMyLoans setUserIp(java.lang.String userIp) {
      return (SelectDtoMyLoans) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public SelectDtoMyLoans setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public SelectDtoMyLoans setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public SelectDtoMyLoans setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public SelectDtoMyLoans set(String parameterName, Object value) {
      return (SelectDtoMyLoans) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "selectMyInvestments".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link SelectMyInvestments#execute()} method to invoke the remote operation.
   *
   * @param email
   * @return the request
   */
  public SelectMyInvestments selectMyInvestments(java.lang.String email) throws java.io.IOException {
    SelectMyInvestments result = new SelectMyInvestments(email);
    initialize(result);
    return result;
  }

  public class SelectMyInvestments extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoan> {

    private static final String REST_PATH = "selectMyInvestments/{email}";

    /**
     * Create a request for the method "selectMyInvestments".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link SelectMyInvestments#execute()} method to invoke the remote
     * operation. <p> {@link SelectMyInvestments#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param email
     * @since 1.13
     */
    protected SelectMyInvestments(java.lang.String email) {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoan.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public SelectMyInvestments setAlt(java.lang.String alt) {
      return (SelectMyInvestments) super.setAlt(alt);
    }

    @Override
    public SelectMyInvestments setFields(java.lang.String fields) {
      return (SelectMyInvestments) super.setFields(fields);
    }

    @Override
    public SelectMyInvestments setKey(java.lang.String key) {
      return (SelectMyInvestments) super.setKey(key);
    }

    @Override
    public SelectMyInvestments setOauthToken(java.lang.String oauthToken) {
      return (SelectMyInvestments) super.setOauthToken(oauthToken);
    }

    @Override
    public SelectMyInvestments setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SelectMyInvestments) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SelectMyInvestments setQuotaUser(java.lang.String quotaUser) {
      return (SelectMyInvestments) super.setQuotaUser(quotaUser);
    }

    @Override
    public SelectMyInvestments setUserIp(java.lang.String userIp) {
      return (SelectMyInvestments) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public SelectMyInvestments setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public SelectMyInvestments setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public SelectMyInvestments setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public SelectMyInvestments set(String parameterName, Object value) {
      return (SelectMyInvestments) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "selectMyLoans".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link SelectMyLoans#execute()} method to invoke the remote operation.
   *
   * @param email
   * @return the request
   */
  public SelectMyLoans selectMyLoans(java.lang.String email) throws java.io.IOException {
    SelectMyLoans result = new SelectMyLoans(email);
    initialize(result);
    return result;
  }

  public class SelectMyLoans extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoan> {

    private static final String REST_PATH = "selectMyLoans/{email}";

    /**
     * Create a request for the method "selectMyLoans".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link SelectMyLoans#execute()} method to invoke the remote
     * operation. <p> {@link SelectMyLoans#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param email
     * @since 1.13
     */
    protected SelectMyLoans(java.lang.String email) {
      super(Loanendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.loanendpoint.model.CollectionResponseLoan.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public SelectMyLoans setAlt(java.lang.String alt) {
      return (SelectMyLoans) super.setAlt(alt);
    }

    @Override
    public SelectMyLoans setFields(java.lang.String fields) {
      return (SelectMyLoans) super.setFields(fields);
    }

    @Override
    public SelectMyLoans setKey(java.lang.String key) {
      return (SelectMyLoans) super.setKey(key);
    }

    @Override
    public SelectMyLoans setOauthToken(java.lang.String oauthToken) {
      return (SelectMyLoans) super.setOauthToken(oauthToken);
    }

    @Override
    public SelectMyLoans setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SelectMyLoans) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SelectMyLoans setQuotaUser(java.lang.String quotaUser) {
      return (SelectMyLoans) super.setQuotaUser(quotaUser);
    }

    @Override
    public SelectMyLoans setUserIp(java.lang.String userIp) {
      return (SelectMyLoans) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public SelectMyLoans setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public SelectMyLoans setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public SelectMyLoans setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public SelectMyLoans set(String parameterName, Object value) {
      return (SelectMyLoans) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateLoan".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link UpdateLoan#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.sp.fanikiwa.entity.loanendpoint.model.Loan}
   * @return the request
   */
  public UpdateLoan updateLoan(com.sp.fanikiwa.entity.loanendpoint.model.Loan content) throws java.io.IOException {
    UpdateLoan result = new UpdateLoan(content);
    initialize(result);
    return result;
  }

  public class UpdateLoan extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.Loan> {

    private static final String REST_PATH = "loan";

    /**
     * Create a request for the method "updateLoan".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link UpdateLoan#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateLoan#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.sp.fanikiwa.entity.loanendpoint.model.Loan}
     * @since 1.13
     */
    protected UpdateLoan(com.sp.fanikiwa.entity.loanendpoint.model.Loan content) {
      super(Loanendpoint.this, "PUT", REST_PATH, content, com.sp.fanikiwa.entity.loanendpoint.model.Loan.class);
    }

    @Override
    public UpdateLoan setAlt(java.lang.String alt) {
      return (UpdateLoan) super.setAlt(alt);
    }

    @Override
    public UpdateLoan setFields(java.lang.String fields) {
      return (UpdateLoan) super.setFields(fields);
    }

    @Override
    public UpdateLoan setKey(java.lang.String key) {
      return (UpdateLoan) super.setKey(key);
    }

    @Override
    public UpdateLoan setOauthToken(java.lang.String oauthToken) {
      return (UpdateLoan) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateLoan setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateLoan) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateLoan setQuotaUser(java.lang.String quotaUser) {
      return (UpdateLoan) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateLoan setUserIp(java.lang.String userIp) {
      return (UpdateLoan) super.setUserIp(userIp);
    }

    @Override
    public UpdateLoan set(String parameterName, Object value) {
      return (UpdateLoan) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "zerolizeAccruedIntLoan".
   *
   * This request holds the parameters needed by the loanendpoint server.  After setting any optional
   * parameters, call the {@link ZerolizeAccruedIntLoan#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.sp.fanikiwa.entity.loanendpoint.model.Loan}
   * @return the request
   */
  public ZerolizeAccruedIntLoan zerolizeAccruedIntLoan(com.sp.fanikiwa.entity.loanendpoint.model.Loan content) throws java.io.IOException {
    ZerolizeAccruedIntLoan result = new ZerolizeAccruedIntLoan(content);
    initialize(result);
    return result;
  }

  public class ZerolizeAccruedIntLoan extends LoanendpointRequest<com.sp.fanikiwa.entity.loanendpoint.model.Loan> {

    private static final String REST_PATH = "zerolizeAccruedIntLoan";

    /**
     * Create a request for the method "zerolizeAccruedIntLoan".
     *
     * This request holds the parameters needed by the the loanendpoint server.  After setting any
     * optional parameters, call the {@link ZerolizeAccruedIntLoan#execute()} method to invoke the
     * remote operation. <p> {@link ZerolizeAccruedIntLoan#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.sp.fanikiwa.entity.loanendpoint.model.Loan}
     * @since 1.13
     */
    protected ZerolizeAccruedIntLoan(com.sp.fanikiwa.entity.loanendpoint.model.Loan content) {
      super(Loanendpoint.this, "POST", REST_PATH, content, com.sp.fanikiwa.entity.loanendpoint.model.Loan.class);
    }

    @Override
    public ZerolizeAccruedIntLoan setAlt(java.lang.String alt) {
      return (ZerolizeAccruedIntLoan) super.setAlt(alt);
    }

    @Override
    public ZerolizeAccruedIntLoan setFields(java.lang.String fields) {
      return (ZerolizeAccruedIntLoan) super.setFields(fields);
    }

    @Override
    public ZerolizeAccruedIntLoan setKey(java.lang.String key) {
      return (ZerolizeAccruedIntLoan) super.setKey(key);
    }

    @Override
    public ZerolizeAccruedIntLoan setOauthToken(java.lang.String oauthToken) {
      return (ZerolizeAccruedIntLoan) super.setOauthToken(oauthToken);
    }

    @Override
    public ZerolizeAccruedIntLoan setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ZerolizeAccruedIntLoan) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ZerolizeAccruedIntLoan setQuotaUser(java.lang.String quotaUser) {
      return (ZerolizeAccruedIntLoan) super.setQuotaUser(quotaUser);
    }

    @Override
    public ZerolizeAccruedIntLoan setUserIp(java.lang.String userIp) {
      return (ZerolizeAccruedIntLoan) super.setUserIp(userIp);
    }

    @Override
    public ZerolizeAccruedIntLoan set(String parameterName, Object value) {
      return (ZerolizeAccruedIntLoan) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Loanendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Loanendpoint}. */
    @Override
    public Loanendpoint build() {
      return new Loanendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link LoanendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setLoanendpointRequestInitializer(
        LoanendpointRequestInitializer loanendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(loanendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
