/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-26 at 12:54:08 UTC 
 * Modify at your own risk.
 */

package com.sp.fanikiwa.entity.contactendpoint.model;

/**
 * Model definition for Contact.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the contactendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Contact extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long contactId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime dateActivated;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime dateJoined;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime dateOfBirth;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gender;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String informBy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nationalID;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String otherNames;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String photo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pwd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer refferedBy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String surname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String telephone;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getContactId() {
    return contactId;
  }

  /**
   * @param contactId contactId or {@code null} for none
   */
  public Contact setContactId(java.lang.Long contactId) {
    this.contactId = contactId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDateActivated() {
    return dateActivated;
  }

  /**
   * @param dateActivated dateActivated or {@code null} for none
   */
  public Contact setDateActivated(com.google.api.client.util.DateTime dateActivated) {
    this.dateActivated = dateActivated;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDateJoined() {
    return dateJoined;
  }

  /**
   * @param dateJoined dateJoined or {@code null} for none
   */
  public Contact setDateJoined(com.google.api.client.util.DateTime dateJoined) {
    this.dateJoined = dateJoined;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDateOfBirth() {
    return dateOfBirth;
  }

  /**
   * @param dateOfBirth dateOfBirth or {@code null} for none
   */
  public Contact setDateOfBirth(com.google.api.client.util.DateTime dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public Contact setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGender() {
    return gender;
  }

  /**
   * @param gender gender or {@code null} for none
   */
  public Contact setGender(java.lang.String gender) {
    this.gender = gender;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInformBy() {
    return informBy;
  }

  /**
   * @param informBy informBy or {@code null} for none
   */
  public Contact setInformBy(java.lang.String informBy) {
    this.informBy = informBy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNationalID() {
    return nationalID;
  }

  /**
   * @param nationalID nationalID or {@code null} for none
   */
  public Contact setNationalID(java.lang.String nationalID) {
    this.nationalID = nationalID;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOtherNames() {
    return otherNames;
  }

  /**
   * @param otherNames otherNames or {@code null} for none
   */
  public Contact setOtherNames(java.lang.String otherNames) {
    this.otherNames = otherNames;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPhoto() {
    return photo;
  }

  /**
   * @param photo photo or {@code null} for none
   */
  public Contact setPhoto(java.lang.String photo) {
    this.photo = photo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPwd() {
    return pwd;
  }

  /**
   * @param pwd pwd or {@code null} for none
   */
  public Contact setPwd(java.lang.String pwd) {
    this.pwd = pwd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRefferedBy() {
    return refferedBy;
  }

  /**
   * @param refferedBy refferedBy or {@code null} for none
   */
  public Contact setRefferedBy(java.lang.Integer refferedBy) {
    this.refferedBy = refferedBy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public Contact setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSurname() {
    return surname;
  }

  /**
   * @param surname surname or {@code null} for none
   */
  public Contact setSurname(java.lang.String surname) {
    this.surname = surname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTelephone() {
    return telephone;
  }

  /**
   * @param telephone telephone or {@code null} for none
   */
  public Contact setTelephone(java.lang.String telephone) {
    this.telephone = telephone;
    return this;
  }

  @Override
  public Contact set(String fieldName, Object value) {
    return (Contact) super.set(fieldName, value);
  }

  @Override
  public Contact clone() {
    return (Contact) super.clone();
  }

}
