/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-26 at 12:50:52 UTC 
 * Modify at your own risk.
 */

package com.sp.fanikiwa.entity.accountendpoint;

/**
 * Service definition for Accountendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AccountendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Accountendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the accountendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://fanikiwaweb.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "accountendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Accountendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Accountendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the AccountEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Accountendpoint accountendpoint = new Accountendpoint(...);}
   *   {@code Accountendpoint.AccountEndpoint.List request = accountendpoint.accountEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public AccountEndpoint accountEndpoint() {
    return new AccountEndpoint();
  }

  /**
   * The "accountEndpoint" collection of methods.
   */
  public class AccountEndpoint {

    /**
     * Create a request for the method "accountEndpoint.clearDaysEffects".
     *
     * This request holds the parameters needed by the accountendpoint server.  After setting any
     * optional parameters, call the {@link ClearDaysEffects#execute()} method to invoke the remote
     * operation.
     *
     * @param date
     * @return the request
     */
    public ClearDaysEffects clearDaysEffects(com.google.api.client.util.DateTime date) throws java.io.IOException {
      ClearDaysEffects result = new ClearDaysEffects(date);
      initialize(result);
      return result;
    }

    public class ClearDaysEffects extends AccountendpointRequest<Void> {

      private static final String REST_PATH = "ClearDaysEffects/{date}";

      /**
       * Create a request for the method "accountEndpoint.clearDaysEffects".
       *
       * This request holds the parameters needed by the the accountendpoint server.  After setting any
       * optional parameters, call the {@link ClearDaysEffects#execute()} method to invoke the remote
       * operation. <p> {@link ClearDaysEffects#initialize(com.google.api.client.googleapis.services.Abs
       * tractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param date
       * @since 1.13
       */
      protected ClearDaysEffects(com.google.api.client.util.DateTime date) {
        super(Accountendpoint.this, "POST", REST_PATH, null, Void.class);
        this.date = com.google.api.client.util.Preconditions.checkNotNull(date, "Required parameter date must be specified.");
      }

      @Override
      public ClearDaysEffects setAlt(java.lang.String alt) {
        return (ClearDaysEffects) super.setAlt(alt);
      }

      @Override
      public ClearDaysEffects setFields(java.lang.String fields) {
        return (ClearDaysEffects) super.setFields(fields);
      }

      @Override
      public ClearDaysEffects setKey(java.lang.String key) {
        return (ClearDaysEffects) super.setKey(key);
      }

      @Override
      public ClearDaysEffects setOauthToken(java.lang.String oauthToken) {
        return (ClearDaysEffects) super.setOauthToken(oauthToken);
      }

      @Override
      public ClearDaysEffects setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (ClearDaysEffects) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public ClearDaysEffects setQuotaUser(java.lang.String quotaUser) {
        return (ClearDaysEffects) super.setQuotaUser(quotaUser);
      }

      @Override
      public ClearDaysEffects setUserIp(java.lang.String userIp) {
        return (ClearDaysEffects) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private com.google.api.client.util.DateTime date;

      /**

       */
      public com.google.api.client.util.DateTime getDate() {
        return date;
      }

      public ClearDaysEffects setDate(com.google.api.client.util.DateTime date) {
        this.date = date;
        return this;
      }

      @Override
      public ClearDaysEffects set(String parameterName, Object value) {
        return (ClearDaysEffects) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "accountEndpoint.simulate".
     *
     * This request holds the parameters needed by the accountendpoint server.  After setting any
     * optional parameters, call the {@link Simulate#execute()} method to invoke the remote operation.
     *
     * @param flags
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry}
     * @return the request
     */
    public Simulate simulate(java.lang.String flags, com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry content) throws java.io.IOException {
      Simulate result = new Simulate(flags, content);
      initialize(result);
      return result;
    }

    public class Simulate extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.BatchSimulateStatus> {

      private static final String REST_PATH = "Simulate/{flags}";

      /**
       * Create a request for the method "accountEndpoint.simulate".
       *
       * This request holds the parameters needed by the the accountendpoint server.  After setting any
       * optional parameters, call the {@link Simulate#execute()} method to invoke the remote operation.
       * <p> {@link
       * Simulate#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param flags
       * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry}
       * @since 1.13
       */
      protected Simulate(java.lang.String flags, com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry content) {
        super(Accountendpoint.this, "POST", REST_PATH, content, com.sp.fanikiwa.entity.accountendpoint.model.BatchSimulateStatus.class);
        this.flags = com.google.api.client.util.Preconditions.checkNotNull(flags, "Required parameter flags must be specified.");
      }

      @Override
      public Simulate setAlt(java.lang.String alt) {
        return (Simulate) super.setAlt(alt);
      }

      @Override
      public Simulate setFields(java.lang.String fields) {
        return (Simulate) super.setFields(fields);
      }

      @Override
      public Simulate setKey(java.lang.String key) {
        return (Simulate) super.setKey(key);
      }

      @Override
      public Simulate setOauthToken(java.lang.String oauthToken) {
        return (Simulate) super.setOauthToken(oauthToken);
      }

      @Override
      public Simulate setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Simulate) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Simulate setQuotaUser(java.lang.String quotaUser) {
        return (Simulate) super.setQuotaUser(quotaUser);
      }

      @Override
      public Simulate setUserIp(java.lang.String userIp) {
        return (Simulate) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String flags;

      /**

       */
      public java.lang.String getFlags() {
        return flags;
      }

      public Simulate setFlags(java.lang.String flags) {
        this.flags = flags;
        return this;
      }

      @Override
      public Simulate set(String parameterName, Object value) {
        return (Simulate) super.set(parameterName, value);
      }
    }

  }

  /**
   * Create a request for the method "batchPost".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link BatchPost#execute()} method to invoke the remote operation.
   *
   * @param flags
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry}
   * @return the request
   */
  public BatchPost batchPost(java.lang.String flags, com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry content) throws java.io.IOException {
    BatchPost result = new BatchPost(flags, content);
    initialize(result);
    return result;
  }

  public class BatchPost extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.RequestResult> {

    private static final String REST_PATH = "BatchPost/{flags}";

    /**
     * Create a request for the method "batchPost".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link BatchPost#execute()} method to invoke the remote
     * operation. <p> {@link
     * BatchPost#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param flags
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry}
     * @since 1.13
     */
    protected BatchPost(java.lang.String flags, com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, com.sp.fanikiwa.entity.accountendpoint.model.RequestResult.class);
      this.flags = com.google.api.client.util.Preconditions.checkNotNull(flags, "Required parameter flags must be specified.");
    }

    @Override
    public BatchPost setAlt(java.lang.String alt) {
      return (BatchPost) super.setAlt(alt);
    }

    @Override
    public BatchPost setFields(java.lang.String fields) {
      return (BatchPost) super.setFields(fields);
    }

    @Override
    public BatchPost setKey(java.lang.String key) {
      return (BatchPost) super.setKey(key);
    }

    @Override
    public BatchPost setOauthToken(java.lang.String oauthToken) {
      return (BatchPost) super.setOauthToken(oauthToken);
    }

    @Override
    public BatchPost setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (BatchPost) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public BatchPost setQuotaUser(java.lang.String quotaUser) {
      return (BatchPost) super.setQuotaUser(quotaUser);
    }

    @Override
    public BatchPost setUserIp(java.lang.String userIp) {
      return (BatchPost) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String flags;

    /**

     */
    public java.lang.String getFlags() {
      return flags;
    }

    public BatchPost setFlags(java.lang.String flags) {
      this.flags = flags;
      return this;
    }

    @Override
    public BatchPost set(String parameterName, Object value) {
      return (BatchPost) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "blockFunds".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link BlockFunds#execute()} method to invoke the remote operation.
   *
   * @param blockamount
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
   * @return the request
   */
  public BlockFunds blockFunds(java.lang.Double blockamount, com.sp.fanikiwa.entity.accountendpoint.model.Account content) throws java.io.IOException {
    BlockFunds result = new BlockFunds(blockamount, content);
    initialize(result);
    return result;
  }

  public class BlockFunds extends AccountendpointRequest<Void> {

    private static final String REST_PATH = "BlockFunds/{blockamount}";

    /**
     * Create a request for the method "blockFunds".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link BlockFunds#execute()} method to invoke the remote
     * operation. <p> {@link
     * BlockFunds#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param blockamount
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
     * @since 1.13
     */
    protected BlockFunds(java.lang.Double blockamount, com.sp.fanikiwa.entity.accountendpoint.model.Account content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, Void.class);
      this.blockamount = com.google.api.client.util.Preconditions.checkNotNull(blockamount, "Required parameter blockamount must be specified.");
    }

    @Override
    public BlockFunds setAlt(java.lang.String alt) {
      return (BlockFunds) super.setAlt(alt);
    }

    @Override
    public BlockFunds setFields(java.lang.String fields) {
      return (BlockFunds) super.setFields(fields);
    }

    @Override
    public BlockFunds setKey(java.lang.String key) {
      return (BlockFunds) super.setKey(key);
    }

    @Override
    public BlockFunds setOauthToken(java.lang.String oauthToken) {
      return (BlockFunds) super.setOauthToken(oauthToken);
    }

    @Override
    public BlockFunds setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (BlockFunds) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public BlockFunds setQuotaUser(java.lang.String quotaUser) {
      return (BlockFunds) super.setQuotaUser(quotaUser);
    }

    @Override
    public BlockFunds setUserIp(java.lang.String userIp) {
      return (BlockFunds) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Double blockamount;

    /**

     */
    public java.lang.Double getBlockamount() {
      return blockamount;
    }

    public BlockFunds setBlockamount(java.lang.Double blockamount) {
      this.blockamount = blockamount;
      return this;
    }

    @Override
    public BlockFunds set(String parameterName, Object value) {
      return (BlockFunds) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "clearEffects".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link ClearEffects#execute()} method to invoke the remote
   * operation.
   *
   * @param amount
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
   * @return the request
   */
  public ClearEffects clearEffects(java.lang.Double amount, com.sp.fanikiwa.entity.accountendpoint.model.Account content) throws java.io.IOException {
    ClearEffects result = new ClearEffects(amount, content);
    initialize(result);
    return result;
  }

  public class ClearEffects extends AccountendpointRequest<Void> {

    private static final String REST_PATH = "ClearEffects/{amount}";

    /**
     * Create a request for the method "clearEffects".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link ClearEffects#execute()} method to invoke the remote
     * operation. <p> {@link
     * ClearEffects#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param amount
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
     * @since 1.13
     */
    protected ClearEffects(java.lang.Double amount, com.sp.fanikiwa.entity.accountendpoint.model.Account content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, Void.class);
      this.amount = com.google.api.client.util.Preconditions.checkNotNull(amount, "Required parameter amount must be specified.");
    }

    @Override
    public ClearEffects setAlt(java.lang.String alt) {
      return (ClearEffects) super.setAlt(alt);
    }

    @Override
    public ClearEffects setFields(java.lang.String fields) {
      return (ClearEffects) super.setFields(fields);
    }

    @Override
    public ClearEffects setKey(java.lang.String key) {
      return (ClearEffects) super.setKey(key);
    }

    @Override
    public ClearEffects setOauthToken(java.lang.String oauthToken) {
      return (ClearEffects) super.setOauthToken(oauthToken);
    }

    @Override
    public ClearEffects setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ClearEffects) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ClearEffects setQuotaUser(java.lang.String quotaUser) {
      return (ClearEffects) super.setQuotaUser(quotaUser);
    }

    @Override
    public ClearEffects setUserIp(java.lang.String userIp) {
      return (ClearEffects) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Double amount;

    /**

     */
    public java.lang.Double getAmount() {
      return amount;
    }

    public ClearEffects setAmount(java.lang.Double amount) {
      this.amount = amount;
      return this;
    }

    @Override
    public ClearEffects set(String parameterName, Object value) {
      return (ClearEffects) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "closeAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link CloseAccount#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
   * @return the request
   */
  public CloseAccount closeAccount(com.sp.fanikiwa.entity.accountendpoint.model.Account content) throws java.io.IOException {
    CloseAccount result = new CloseAccount(content);
    initialize(result);
    return result;
  }

  public class CloseAccount extends AccountendpointRequest<Void> {

    private static final String REST_PATH = "CloseAccount";

    /**
     * Create a request for the method "closeAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link CloseAccount#execute()} method to invoke the remote
     * operation. <p> {@link
     * CloseAccount#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
     * @since 1.13
     */
    protected CloseAccount(com.sp.fanikiwa.entity.accountendpoint.model.Account content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, Void.class);
    }

    @Override
    public CloseAccount setAlt(java.lang.String alt) {
      return (CloseAccount) super.setAlt(alt);
    }

    @Override
    public CloseAccount setFields(java.lang.String fields) {
      return (CloseAccount) super.setFields(fields);
    }

    @Override
    public CloseAccount setKey(java.lang.String key) {
      return (CloseAccount) super.setKey(key);
    }

    @Override
    public CloseAccount setOauthToken(java.lang.String oauthToken) {
      return (CloseAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public CloseAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (CloseAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CloseAccount setQuotaUser(java.lang.String quotaUser) {
      return (CloseAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public CloseAccount setUserIp(java.lang.String userIp) {
      return (CloseAccount) super.setUserIp(userIp);
    }

    @Override
    public CloseAccount set(String parameterName, Object value) {
      return (CloseAccount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "doubleEntryPost".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link DoubleEntryPost#execute()} method to invoke the remote
   * operation.
   *
   * @param flags
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.DoubleEntry}
   * @return the request
   */
  public DoubleEntryPost doubleEntryPost(java.lang.String flags, com.sp.fanikiwa.entity.accountendpoint.model.DoubleEntry content) throws java.io.IOException {
    DoubleEntryPost result = new DoubleEntryPost(flags, content);
    initialize(result);
    return result;
  }

  public class DoubleEntryPost extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.RequestResult> {

    private static final String REST_PATH = "DoubleEntryPost/{flags}";

    /**
     * Create a request for the method "doubleEntryPost".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link DoubleEntryPost#execute()} method to invoke the remote
     * operation. <p> {@link DoubleEntryPost#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param flags
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.DoubleEntry}
     * @since 1.13
     */
    protected DoubleEntryPost(java.lang.String flags, com.sp.fanikiwa.entity.accountendpoint.model.DoubleEntry content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, com.sp.fanikiwa.entity.accountendpoint.model.RequestResult.class);
      this.flags = com.google.api.client.util.Preconditions.checkNotNull(flags, "Required parameter flags must be specified.");
    }

    @Override
    public DoubleEntryPost setAlt(java.lang.String alt) {
      return (DoubleEntryPost) super.setAlt(alt);
    }

    @Override
    public DoubleEntryPost setFields(java.lang.String fields) {
      return (DoubleEntryPost) super.setFields(fields);
    }

    @Override
    public DoubleEntryPost setKey(java.lang.String key) {
      return (DoubleEntryPost) super.setKey(key);
    }

    @Override
    public DoubleEntryPost setOauthToken(java.lang.String oauthToken) {
      return (DoubleEntryPost) super.setOauthToken(oauthToken);
    }

    @Override
    public DoubleEntryPost setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (DoubleEntryPost) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public DoubleEntryPost setQuotaUser(java.lang.String quotaUser) {
      return (DoubleEntryPost) super.setQuotaUser(quotaUser);
    }

    @Override
    public DoubleEntryPost setUserIp(java.lang.String userIp) {
      return (DoubleEntryPost) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String flags;

    /**

     */
    public java.lang.String getFlags() {
      return flags;
    }

    public DoubleEntryPost setFlags(java.lang.String flags) {
      this.flags = flags;
      return this;
    }

    @Override
    public DoubleEntryPost set(String parameterName, Object value) {
      return (DoubleEntryPost) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link GetAccount#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetAccount getAccount(java.lang.Long id) throws java.io.IOException {
    GetAccount result = new GetAccount(id);
    initialize(result);
    return result;
  }

  public class GetAccount extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.Account> {

    private static final String REST_PATH = "account/{id}";

    /**
     * Create a request for the method "getAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link GetAccount#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetAccount#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAccount(java.lang.Long id) {
      super(Accountendpoint.this, "GET", REST_PATH, null, com.sp.fanikiwa.entity.accountendpoint.model.Account.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAccount setAlt(java.lang.String alt) {
      return (GetAccount) super.setAlt(alt);
    }

    @Override
    public GetAccount setFields(java.lang.String fields) {
      return (GetAccount) super.setFields(fields);
    }

    @Override
    public GetAccount setKey(java.lang.String key) {
      return (GetAccount) super.setKey(key);
    }

    @Override
    public GetAccount setOauthToken(java.lang.String oauthToken) {
      return (GetAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAccount setQuotaUser(java.lang.String quotaUser) {
      return (GetAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAccount setUserIp(java.lang.String userIp) {
      return (GetAccount) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetAccount setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAccount set(String parameterName, Object value) {
      return (GetAccount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link InsertAccount#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
   * @return the request
   */
  public InsertAccount insertAccount(com.sp.fanikiwa.entity.accountendpoint.model.Account content) throws java.io.IOException {
    InsertAccount result = new InsertAccount(content);
    initialize(result);
    return result;
  }

  public class InsertAccount extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.Account> {

    private static final String REST_PATH = "account";

    /**
     * Create a request for the method "insertAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link InsertAccount#execute()} method to invoke the remote
     * operation. <p> {@link InsertAccount#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
     * @since 1.13
     */
    protected InsertAccount(com.sp.fanikiwa.entity.accountendpoint.model.Account content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, com.sp.fanikiwa.entity.accountendpoint.model.Account.class);
    }

    @Override
    public InsertAccount setAlt(java.lang.String alt) {
      return (InsertAccount) super.setAlt(alt);
    }

    @Override
    public InsertAccount setFields(java.lang.String fields) {
      return (InsertAccount) super.setFields(fields);
    }

    @Override
    public InsertAccount setKey(java.lang.String key) {
      return (InsertAccount) super.setKey(key);
    }

    @Override
    public InsertAccount setOauthToken(java.lang.String oauthToken) {
      return (InsertAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAccount setQuotaUser(java.lang.String quotaUser) {
      return (InsertAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAccount setUserIp(java.lang.String userIp) {
      return (InsertAccount) super.setUserIp(userIp);
    }

    @Override
    public InsertAccount set(String parameterName, Object value) {
      return (InsertAccount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link ListAccount#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAccount listAccount() throws java.io.IOException {
    ListAccount result = new ListAccount();
    initialize(result);
    return result;
  }

  public class ListAccount extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.CollectionResponseAccount> {

    private static final String REST_PATH = "account";

    /**
     * Create a request for the method "listAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link ListAccount#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListAccount#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAccount() {
      super(Accountendpoint.this, "GET", REST_PATH, null, com.sp.fanikiwa.entity.accountendpoint.model.CollectionResponseAccount.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAccount setAlt(java.lang.String alt) {
      return (ListAccount) super.setAlt(alt);
    }

    @Override
    public ListAccount setFields(java.lang.String fields) {
      return (ListAccount) super.setFields(fields);
    }

    @Override
    public ListAccount setKey(java.lang.String key) {
      return (ListAccount) super.setKey(key);
    }

    @Override
    public ListAccount setOauthToken(java.lang.String oauthToken) {
      return (ListAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAccount setQuotaUser(java.lang.String quotaUser) {
      return (ListAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAccount setUserIp(java.lang.String userIp) {
      return (ListAccount) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public ListAccount setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAccount setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public ListAccount set(String parameterName, Object value) {
      return (ListAccount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "miniStatement".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link MiniStatement#execute()} method to invoke the remote
   * operation.
   *
   * @param accountID
   * @return the request
   */
  public MiniStatement miniStatement(java.lang.Long accountID) throws java.io.IOException {
    MiniStatement result = new MiniStatement(accountID);
    initialize(result);
    return result;
  }

  public class MiniStatement extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.CollectionResponseStatementModel> {

    private static final String REST_PATH = "GetMiniStatement/{accountID}";

    /**
     * Create a request for the method "miniStatement".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link MiniStatement#execute()} method to invoke the remote
     * operation. <p> {@link MiniStatement#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param accountID
     * @since 1.13
     */
    protected MiniStatement(java.lang.Long accountID) {
      super(Accountendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.accountendpoint.model.CollectionResponseStatementModel.class);
      this.accountID = com.google.api.client.util.Preconditions.checkNotNull(accountID, "Required parameter accountID must be specified.");
    }

    @Override
    public MiniStatement setAlt(java.lang.String alt) {
      return (MiniStatement) super.setAlt(alt);
    }

    @Override
    public MiniStatement setFields(java.lang.String fields) {
      return (MiniStatement) super.setFields(fields);
    }

    @Override
    public MiniStatement setKey(java.lang.String key) {
      return (MiniStatement) super.setKey(key);
    }

    @Override
    public MiniStatement setOauthToken(java.lang.String oauthToken) {
      return (MiniStatement) super.setOauthToken(oauthToken);
    }

    @Override
    public MiniStatement setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (MiniStatement) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public MiniStatement setQuotaUser(java.lang.String quotaUser) {
      return (MiniStatement) super.setQuotaUser(quotaUser);
    }

    @Override
    public MiniStatement setUserIp(java.lang.String userIp) {
      return (MiniStatement) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long accountID;

    /**

     */
    public java.lang.Long getAccountID() {
      return accountID;
    }

    public MiniStatement setAccountID(java.lang.Long accountID) {
      this.accountID = accountID;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public MiniStatement setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public MiniStatement setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public MiniStatement set(String parameterName, Object value) {
      return (MiniStatement) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "nextIntAccrualAccountsByDate".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link NextIntAccrualAccountsByDate#execute()} method to invoke the
   * remote operation.
   *
   * @param date
   * @return the request
   */
  public NextIntAccrualAccountsByDate nextIntAccrualAccountsByDate(com.google.api.client.util.DateTime date) throws java.io.IOException {
    NextIntAccrualAccountsByDate result = new NextIntAccrualAccountsByDate(date);
    initialize(result);
    return result;
  }

  public class NextIntAccrualAccountsByDate extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.CollectionResponseAccount> {

    private static final String REST_PATH = "NextIntAccrualAccountsByDate/{date}";

    /**
     * Create a request for the method "nextIntAccrualAccountsByDate".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link NextIntAccrualAccountsByDate#execute()} method to invoke
     * the remote operation. <p> {@link NextIntAccrualAccountsByDate#initialize(com.google.api.client.
     * googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param date
     * @since 1.13
     */
    protected NextIntAccrualAccountsByDate(com.google.api.client.util.DateTime date) {
      super(Accountendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.accountendpoint.model.CollectionResponseAccount.class);
      this.date = com.google.api.client.util.Preconditions.checkNotNull(date, "Required parameter date must be specified.");
    }

    @Override
    public NextIntAccrualAccountsByDate setAlt(java.lang.String alt) {
      return (NextIntAccrualAccountsByDate) super.setAlt(alt);
    }

    @Override
    public NextIntAccrualAccountsByDate setFields(java.lang.String fields) {
      return (NextIntAccrualAccountsByDate) super.setFields(fields);
    }

    @Override
    public NextIntAccrualAccountsByDate setKey(java.lang.String key) {
      return (NextIntAccrualAccountsByDate) super.setKey(key);
    }

    @Override
    public NextIntAccrualAccountsByDate setOauthToken(java.lang.String oauthToken) {
      return (NextIntAccrualAccountsByDate) super.setOauthToken(oauthToken);
    }

    @Override
    public NextIntAccrualAccountsByDate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (NextIntAccrualAccountsByDate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public NextIntAccrualAccountsByDate setQuotaUser(java.lang.String quotaUser) {
      return (NextIntAccrualAccountsByDate) super.setQuotaUser(quotaUser);
    }

    @Override
    public NextIntAccrualAccountsByDate setUserIp(java.lang.String userIp) {
      return (NextIntAccrualAccountsByDate) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime date;

    /**

     */
    public com.google.api.client.util.DateTime getDate() {
      return date;
    }

    public NextIntAccrualAccountsByDate setDate(com.google.api.client.util.DateTime date) {
      this.date = date;
      return this;
    }

    @Override
    public NextIntAccrualAccountsByDate set(String parameterName, Object value) {
      return (NextIntAccrualAccountsByDate) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "nextIntAppAccountsByDate".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link NextIntAppAccountsByDate#execute()} method to invoke the
   * remote operation.
   *
   * @param date
   * @return the request
   */
  public NextIntAppAccountsByDate nextIntAppAccountsByDate(com.google.api.client.util.DateTime date) throws java.io.IOException {
    NextIntAppAccountsByDate result = new NextIntAppAccountsByDate(date);
    initialize(result);
    return result;
  }

  public class NextIntAppAccountsByDate extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.CollectionResponseAccount> {

    private static final String REST_PATH = "NextIntAppAccountsByDate/{date}";

    /**
     * Create a request for the method "nextIntAppAccountsByDate".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link NextIntAppAccountsByDate#execute()} method to invoke the
     * remote operation. <p> {@link NextIntAppAccountsByDate#initialize(com.google.api.client.googleap
     * is.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param date
     * @since 1.13
     */
    protected NextIntAppAccountsByDate(com.google.api.client.util.DateTime date) {
      super(Accountendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.accountendpoint.model.CollectionResponseAccount.class);
      this.date = com.google.api.client.util.Preconditions.checkNotNull(date, "Required parameter date must be specified.");
    }

    @Override
    public NextIntAppAccountsByDate setAlt(java.lang.String alt) {
      return (NextIntAppAccountsByDate) super.setAlt(alt);
    }

    @Override
    public NextIntAppAccountsByDate setFields(java.lang.String fields) {
      return (NextIntAppAccountsByDate) super.setFields(fields);
    }

    @Override
    public NextIntAppAccountsByDate setKey(java.lang.String key) {
      return (NextIntAppAccountsByDate) super.setKey(key);
    }

    @Override
    public NextIntAppAccountsByDate setOauthToken(java.lang.String oauthToken) {
      return (NextIntAppAccountsByDate) super.setOauthToken(oauthToken);
    }

    @Override
    public NextIntAppAccountsByDate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (NextIntAppAccountsByDate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public NextIntAppAccountsByDate setQuotaUser(java.lang.String quotaUser) {
      return (NextIntAppAccountsByDate) super.setQuotaUser(quotaUser);
    }

    @Override
    public NextIntAppAccountsByDate setUserIp(java.lang.String userIp) {
      return (NextIntAppAccountsByDate) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime date;

    /**

     */
    public com.google.api.client.util.DateTime getDate() {
      return date;
    }

    public NextIntAppAccountsByDate setDate(com.google.api.client.util.DateTime date) {
      this.date = date;
      return this;
    }

    @Override
    public NextIntAppAccountsByDate set(String parameterName, Object value) {
      return (NextIntAppAccountsByDate) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "post".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link Post#execute()} method to invoke the remote operation.
   *
   * @param flags
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Transaction}
   * @return the request
   */
  public Post post(java.lang.String flags, com.sp.fanikiwa.entity.accountendpoint.model.Transaction content) throws java.io.IOException {
    Post result = new Post(flags, content);
    initialize(result);
    return result;
  }

  public class Post extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.RequestResult> {

    private static final String REST_PATH = "Post/{flags}";

    /**
     * Create a request for the method "post".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link Post#execute()} method to invoke the remote operation. <p>
     * {@link Post#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param flags
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Transaction}
     * @since 1.13
     */
    protected Post(java.lang.String flags, com.sp.fanikiwa.entity.accountendpoint.model.Transaction content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, com.sp.fanikiwa.entity.accountendpoint.model.RequestResult.class);
      this.flags = com.google.api.client.util.Preconditions.checkNotNull(flags, "Required parameter flags must be specified.");
    }

    @Override
    public Post setAlt(java.lang.String alt) {
      return (Post) super.setAlt(alt);
    }

    @Override
    public Post setFields(java.lang.String fields) {
      return (Post) super.setFields(fields);
    }

    @Override
    public Post setKey(java.lang.String key) {
      return (Post) super.setKey(key);
    }

    @Override
    public Post setOauthToken(java.lang.String oauthToken) {
      return (Post) super.setOauthToken(oauthToken);
    }

    @Override
    public Post setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Post) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Post setQuotaUser(java.lang.String quotaUser) {
      return (Post) super.setQuotaUser(quotaUser);
    }

    @Override
    public Post setUserIp(java.lang.String userIp) {
      return (Post) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String flags;

    /**

     */
    public java.lang.String getFlags() {
      return flags;
    }

    public Post setFlags(java.lang.String flags) {
      this.flags = flags;
      return this;
    }

    @Override
    public Post set(String parameterName, Object value) {
      return (Post) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAccount#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAccount removeAccount(java.lang.Long id) throws java.io.IOException {
    RemoveAccount result = new RemoveAccount(id);
    initialize(result);
    return result;
  }

  public class RemoveAccount extends AccountendpointRequest<Void> {

    private static final String REST_PATH = "account/{id}";

    /**
     * Create a request for the method "removeAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link RemoveAccount#execute()} method to invoke the remote
     * operation. <p> {@link RemoveAccount#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAccount(java.lang.Long id) {
      super(Accountendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAccount setAlt(java.lang.String alt) {
      return (RemoveAccount) super.setAlt(alt);
    }

    @Override
    public RemoveAccount setFields(java.lang.String fields) {
      return (RemoveAccount) super.setFields(fields);
    }

    @Override
    public RemoveAccount setKey(java.lang.String key) {
      return (RemoveAccount) super.setKey(key);
    }

    @Override
    public RemoveAccount setOauthToken(java.lang.String oauthToken) {
      return (RemoveAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAccount setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAccount setUserIp(java.lang.String userIp) {
      return (RemoveAccount) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveAccount setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAccount set(String parameterName, Object value) {
      return (RemoveAccount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "setAccountLimitStatus".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link SetAccountLimitStatus#execute()} method to invoke the remote
   * operation.
   *
   * @param status
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
   * @return the request
   */
  public SetAccountLimitStatus setAccountLimitStatus(java.lang.String status, com.sp.fanikiwa.entity.accountendpoint.model.Account content) throws java.io.IOException {
    SetAccountLimitStatus result = new SetAccountLimitStatus(status, content);
    initialize(result);
    return result;
  }

  public class SetAccountLimitStatus extends AccountendpointRequest<Void> {

    private static final String REST_PATH = "SetAccountLimitStatus/{status}";

    /**
     * Create a request for the method "setAccountLimitStatus".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link SetAccountLimitStatus#execute()} method to invoke the
     * remote operation. <p> {@link SetAccountLimitStatus#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param status
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
     * @since 1.13
     */
    protected SetAccountLimitStatus(java.lang.String status, com.sp.fanikiwa.entity.accountendpoint.model.Account content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, Void.class);
      this.status = com.google.api.client.util.Preconditions.checkNotNull(status, "Required parameter status must be specified.");
    }

    @Override
    public SetAccountLimitStatus setAlt(java.lang.String alt) {
      return (SetAccountLimitStatus) super.setAlt(alt);
    }

    @Override
    public SetAccountLimitStatus setFields(java.lang.String fields) {
      return (SetAccountLimitStatus) super.setFields(fields);
    }

    @Override
    public SetAccountLimitStatus setKey(java.lang.String key) {
      return (SetAccountLimitStatus) super.setKey(key);
    }

    @Override
    public SetAccountLimitStatus setOauthToken(java.lang.String oauthToken) {
      return (SetAccountLimitStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public SetAccountLimitStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SetAccountLimitStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SetAccountLimitStatus setQuotaUser(java.lang.String quotaUser) {
      return (SetAccountLimitStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public SetAccountLimitStatus setUserIp(java.lang.String userIp) {
      return (SetAccountLimitStatus) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String status;

    /**

     */
    public java.lang.String getStatus() {
      return status;
    }

    public SetAccountLimitStatus setStatus(java.lang.String status) {
      this.status = status;
      return this;
    }

    @Override
    public SetAccountLimitStatus set(String parameterName, Object value) {
      return (SetAccountLimitStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "setAccountLockStatus".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link SetAccountLockStatus#execute()} method to invoke the remote
   * operation.
   *
   * @param status
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
   * @return the request
   */
  public SetAccountLockStatus setAccountLockStatus(java.lang.String status, com.sp.fanikiwa.entity.accountendpoint.model.Account content) throws java.io.IOException {
    SetAccountLockStatus result = new SetAccountLockStatus(status, content);
    initialize(result);
    return result;
  }

  public class SetAccountLockStatus extends AccountendpointRequest<Void> {

    private static final String REST_PATH = "SetAccountLockStatus/{status}";

    /**
     * Create a request for the method "setAccountLockStatus".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link SetAccountLockStatus#execute()} method to invoke the
     * remote operation. <p> {@link SetAccountLockStatus#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param status
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
     * @since 1.13
     */
    protected SetAccountLockStatus(java.lang.String status, com.sp.fanikiwa.entity.accountendpoint.model.Account content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, Void.class);
      this.status = com.google.api.client.util.Preconditions.checkNotNull(status, "Required parameter status must be specified.");
    }

    @Override
    public SetAccountLockStatus setAlt(java.lang.String alt) {
      return (SetAccountLockStatus) super.setAlt(alt);
    }

    @Override
    public SetAccountLockStatus setFields(java.lang.String fields) {
      return (SetAccountLockStatus) super.setFields(fields);
    }

    @Override
    public SetAccountLockStatus setKey(java.lang.String key) {
      return (SetAccountLockStatus) super.setKey(key);
    }

    @Override
    public SetAccountLockStatus setOauthToken(java.lang.String oauthToken) {
      return (SetAccountLockStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public SetAccountLockStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SetAccountLockStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SetAccountLockStatus setQuotaUser(java.lang.String quotaUser) {
      return (SetAccountLockStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public SetAccountLockStatus setUserIp(java.lang.String userIp) {
      return (SetAccountLockStatus) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String status;

    /**

     */
    public java.lang.String getStatus() {
      return status;
    }

    public SetAccountLockStatus setStatus(java.lang.String status) {
      this.status = status;
      return this;
    }

    @Override
    public SetAccountLockStatus set(String parameterName, Object value) {
      return (SetAccountLockStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "simulatePost".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link SimulatePost#execute()} method to invoke the remote
   * operation.
   *
   * @param flags
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry}
   * @return the request
   */
  public SimulatePost simulatePost(java.lang.String flags, com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry content) throws java.io.IOException {
    SimulatePost result = new SimulatePost(flags, content);
    initialize(result);
    return result;
  }

  public class SimulatePost extends AccountendpointRequest<Void> {

    private static final String REST_PATH = "SimulatePost/{flags}";

    /**
     * Create a request for the method "simulatePost".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link SimulatePost#execute()} method to invoke the remote
     * operation. <p> {@link
     * SimulatePost#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param flags
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry}
     * @since 1.13
     */
    protected SimulatePost(java.lang.String flags, com.sp.fanikiwa.entity.accountendpoint.model.MultiEntry content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, Void.class);
      this.flags = com.google.api.client.util.Preconditions.checkNotNull(flags, "Required parameter flags must be specified.");
    }

    @Override
    public SimulatePost setAlt(java.lang.String alt) {
      return (SimulatePost) super.setAlt(alt);
    }

    @Override
    public SimulatePost setFields(java.lang.String fields) {
      return (SimulatePost) super.setFields(fields);
    }

    @Override
    public SimulatePost setKey(java.lang.String key) {
      return (SimulatePost) super.setKey(key);
    }

    @Override
    public SimulatePost setOauthToken(java.lang.String oauthToken) {
      return (SimulatePost) super.setOauthToken(oauthToken);
    }

    @Override
    public SimulatePost setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SimulatePost) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SimulatePost setQuotaUser(java.lang.String quotaUser) {
      return (SimulatePost) super.setQuotaUser(quotaUser);
    }

    @Override
    public SimulatePost setUserIp(java.lang.String userIp) {
      return (SimulatePost) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String flags;

    /**

     */
    public java.lang.String getFlags() {
      return flags;
    }

    public SimulatePost setFlags(java.lang.String flags) {
      this.flags = flags;
      return this;
    }

    @Override
    public SimulatePost set(String parameterName, Object value) {
      return (SimulatePost) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "statement".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link Statement#execute()} method to invoke the remote operation.
   *
   * @param accountID
   * @param sdate
   * @param edate
   * @return the request
   */
  public Statement statement(java.lang.Long accountID, com.google.api.client.util.DateTime sdate, com.google.api.client.util.DateTime edate) throws java.io.IOException {
    Statement result = new Statement(accountID, sdate, edate);
    initialize(result);
    return result;
  }

  public class Statement extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.CollectionResponseStatementModel> {

    private static final String REST_PATH = "GetStatement/{accountID}/{sdate}/{edate}";

    /**
     * Create a request for the method "statement".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link Statement#execute()} method to invoke the remote
     * operation. <p> {@link
     * Statement#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param accountID
     * @param sdate
     * @param edate
     * @since 1.13
     */
    protected Statement(java.lang.Long accountID, com.google.api.client.util.DateTime sdate, com.google.api.client.util.DateTime edate) {
      super(Accountendpoint.this, "POST", REST_PATH, null, com.sp.fanikiwa.entity.accountendpoint.model.CollectionResponseStatementModel.class);
      this.accountID = com.google.api.client.util.Preconditions.checkNotNull(accountID, "Required parameter accountID must be specified.");
      this.sdate = com.google.api.client.util.Preconditions.checkNotNull(sdate, "Required parameter sdate must be specified.");
      this.edate = com.google.api.client.util.Preconditions.checkNotNull(edate, "Required parameter edate must be specified.");
    }

    @Override
    public Statement setAlt(java.lang.String alt) {
      return (Statement) super.setAlt(alt);
    }

    @Override
    public Statement setFields(java.lang.String fields) {
      return (Statement) super.setFields(fields);
    }

    @Override
    public Statement setKey(java.lang.String key) {
      return (Statement) super.setKey(key);
    }

    @Override
    public Statement setOauthToken(java.lang.String oauthToken) {
      return (Statement) super.setOauthToken(oauthToken);
    }

    @Override
    public Statement setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Statement) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Statement setQuotaUser(java.lang.String quotaUser) {
      return (Statement) super.setQuotaUser(quotaUser);
    }

    @Override
    public Statement setUserIp(java.lang.String userIp) {
      return (Statement) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long accountID;

    /**

     */
    public java.lang.Long getAccountID() {
      return accountID;
    }

    public Statement setAccountID(java.lang.Long accountID) {
      this.accountID = accountID;
      return this;
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime sdate;

    /**

     */
    public com.google.api.client.util.DateTime getSdate() {
      return sdate;
    }

    public Statement setSdate(com.google.api.client.util.DateTime sdate) {
      this.sdate = sdate;
      return this;
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime edate;

    /**

     */
    public com.google.api.client.util.DateTime getEdate() {
      return edate;
    }

    public Statement setEdate(com.google.api.client.util.DateTime edate) {
      this.edate = edate;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public Statement setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public Statement setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public Statement set(String parameterName, Object value) {
      return (Statement) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "unBlockFunds".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link UnBlockFunds#execute()} method to invoke the remote
   * operation.
   *
   * @param amount
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
   * @return the request
   */
  public UnBlockFunds unBlockFunds(java.lang.Double amount, com.sp.fanikiwa.entity.accountendpoint.model.Account content) throws java.io.IOException {
    UnBlockFunds result = new UnBlockFunds(amount, content);
    initialize(result);
    return result;
  }

  public class UnBlockFunds extends AccountendpointRequest<Void> {

    private static final String REST_PATH = "UnBlockFunds/{amount}";

    /**
     * Create a request for the method "unBlockFunds".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link UnBlockFunds#execute()} method to invoke the remote
     * operation. <p> {@link
     * UnBlockFunds#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param amount
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
     * @since 1.13
     */
    protected UnBlockFunds(java.lang.Double amount, com.sp.fanikiwa.entity.accountendpoint.model.Account content) {
      super(Accountendpoint.this, "POST", REST_PATH, content, Void.class);
      this.amount = com.google.api.client.util.Preconditions.checkNotNull(amount, "Required parameter amount must be specified.");
    }

    @Override
    public UnBlockFunds setAlt(java.lang.String alt) {
      return (UnBlockFunds) super.setAlt(alt);
    }

    @Override
    public UnBlockFunds setFields(java.lang.String fields) {
      return (UnBlockFunds) super.setFields(fields);
    }

    @Override
    public UnBlockFunds setKey(java.lang.String key) {
      return (UnBlockFunds) super.setKey(key);
    }

    @Override
    public UnBlockFunds setOauthToken(java.lang.String oauthToken) {
      return (UnBlockFunds) super.setOauthToken(oauthToken);
    }

    @Override
    public UnBlockFunds setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UnBlockFunds) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UnBlockFunds setQuotaUser(java.lang.String quotaUser) {
      return (UnBlockFunds) super.setQuotaUser(quotaUser);
    }

    @Override
    public UnBlockFunds setUserIp(java.lang.String userIp) {
      return (UnBlockFunds) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Double amount;

    /**

     */
    public java.lang.Double getAmount() {
      return amount;
    }

    public UnBlockFunds setAmount(java.lang.Double amount) {
      this.amount = amount;
      return this;
    }

    @Override
    public UnBlockFunds set(String parameterName, Object value) {
      return (UnBlockFunds) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAccount".
   *
   * This request holds the parameters needed by the accountendpoint server.  After setting any
   * optional parameters, call the {@link UpdateAccount#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
   * @return the request
   */
  public UpdateAccount updateAccount(com.sp.fanikiwa.entity.accountendpoint.model.Account content) throws java.io.IOException {
    UpdateAccount result = new UpdateAccount(content);
    initialize(result);
    return result;
  }

  public class UpdateAccount extends AccountendpointRequest<com.sp.fanikiwa.entity.accountendpoint.model.Account> {

    private static final String REST_PATH = "account";

    /**
     * Create a request for the method "updateAccount".
     *
     * This request holds the parameters needed by the the accountendpoint server.  After setting any
     * optional parameters, call the {@link UpdateAccount#execute()} method to invoke the remote
     * operation. <p> {@link UpdateAccount#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.sp.fanikiwa.entity.accountendpoint.model.Account}
     * @since 1.13
     */
    protected UpdateAccount(com.sp.fanikiwa.entity.accountendpoint.model.Account content) {
      super(Accountendpoint.this, "PUT", REST_PATH, content, com.sp.fanikiwa.entity.accountendpoint.model.Account.class);
    }

    @Override
    public UpdateAccount setAlt(java.lang.String alt) {
      return (UpdateAccount) super.setAlt(alt);
    }

    @Override
    public UpdateAccount setFields(java.lang.String fields) {
      return (UpdateAccount) super.setFields(fields);
    }

    @Override
    public UpdateAccount setKey(java.lang.String key) {
      return (UpdateAccount) super.setKey(key);
    }

    @Override
    public UpdateAccount setOauthToken(java.lang.String oauthToken) {
      return (UpdateAccount) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAccount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAccount setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAccount) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAccount setUserIp(java.lang.String userIp) {
      return (UpdateAccount) super.setUserIp(userIp);
    }

    @Override
    public UpdateAccount set(String parameterName, Object value) {
      return (UpdateAccount) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Accountendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Accountendpoint}. */
    @Override
    public Accountendpoint build() {
      return new Accountendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AccountendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAccountendpointRequestInitializer(
        AccountendpointRequestInitializer accountendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(accountendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
