/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-13 at 06:46:19 UTC 
 * Modify at your own risk.
 */

package com.sp.fanikiwa.entity.coaendpoint;

/**
 * Service definition for Coaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CoaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Coaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the coaendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://1-dot-fanikiwaweb.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "coaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Coaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Coaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getCoaByID".
   *
   * This request holds the parameters needed by the coaendpoint server.  After setting any optional
   * parameters, call the {@link GetCoaByID#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetCoaByID getCoaByID(java.lang.Long id) throws java.io.IOException {
    GetCoaByID result = new GetCoaByID(id);
    initialize(result);
    return result;
  }

  public class GetCoaByID extends CoaendpointRequest<com.sp.fanikiwa.entity.coaendpoint.model.Coa> {

    private static final String REST_PATH = "coa/{id}";

    /**
     * Create a request for the method "getCoaByID".
     *
     * This request holds the parameters needed by the the coaendpoint server.  After setting any
     * optional parameters, call the {@link GetCoaByID#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetCoaByID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetCoaByID(java.lang.Long id) {
      super(Coaendpoint.this, "GET", REST_PATH, null, com.sp.fanikiwa.entity.coaendpoint.model.Coa.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCoaByID setAlt(java.lang.String alt) {
      return (GetCoaByID) super.setAlt(alt);
    }

    @Override
    public GetCoaByID setFields(java.lang.String fields) {
      return (GetCoaByID) super.setFields(fields);
    }

    @Override
    public GetCoaByID setKey(java.lang.String key) {
      return (GetCoaByID) super.setKey(key);
    }

    @Override
    public GetCoaByID setOauthToken(java.lang.String oauthToken) {
      return (GetCoaByID) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCoaByID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCoaByID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCoaByID setQuotaUser(java.lang.String quotaUser) {
      return (GetCoaByID) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCoaByID setUserIp(java.lang.String userIp) {
      return (GetCoaByID) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetCoaByID setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetCoaByID set(String parameterName, Object value) {
      return (GetCoaByID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertCoa".
   *
   * This request holds the parameters needed by the coaendpoint server.  After setting any optional
   * parameters, call the {@link InsertCoa#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.sp.fanikiwa.entity.coaendpoint.model.Coa}
   * @return the request
   */
  public InsertCoa insertCoa(com.sp.fanikiwa.entity.coaendpoint.model.Coa content) throws java.io.IOException {
    InsertCoa result = new InsertCoa(content);
    initialize(result);
    return result;
  }

  public class InsertCoa extends CoaendpointRequest<com.sp.fanikiwa.entity.coaendpoint.model.Coa> {

    private static final String REST_PATH = "coa";

    /**
     * Create a request for the method "insertCoa".
     *
     * This request holds the parameters needed by the the coaendpoint server.  After setting any
     * optional parameters, call the {@link InsertCoa#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertCoa#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.sp.fanikiwa.entity.coaendpoint.model.Coa}
     * @since 1.13
     */
    protected InsertCoa(com.sp.fanikiwa.entity.coaendpoint.model.Coa content) {
      super(Coaendpoint.this, "POST", REST_PATH, content, com.sp.fanikiwa.entity.coaendpoint.model.Coa.class);
    }

    @Override
    public InsertCoa setAlt(java.lang.String alt) {
      return (InsertCoa) super.setAlt(alt);
    }

    @Override
    public InsertCoa setFields(java.lang.String fields) {
      return (InsertCoa) super.setFields(fields);
    }

    @Override
    public InsertCoa setKey(java.lang.String key) {
      return (InsertCoa) super.setKey(key);
    }

    @Override
    public InsertCoa setOauthToken(java.lang.String oauthToken) {
      return (InsertCoa) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertCoa setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertCoa) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertCoa setQuotaUser(java.lang.String quotaUser) {
      return (InsertCoa) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertCoa setUserIp(java.lang.String userIp) {
      return (InsertCoa) super.setUserIp(userIp);
    }

    @Override
    public InsertCoa set(String parameterName, Object value) {
      return (InsertCoa) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCoa".
   *
   * This request holds the parameters needed by the coaendpoint server.  After setting any optional
   * parameters, call the {@link ListCoa#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListCoa listCoa() throws java.io.IOException {
    ListCoa result = new ListCoa();
    initialize(result);
    return result;
  }

  public class ListCoa extends CoaendpointRequest<com.sp.fanikiwa.entity.coaendpoint.model.CollectionResponseCoa> {

    private static final String REST_PATH = "coa";

    /**
     * Create a request for the method "listCoa".
     *
     * This request holds the parameters needed by the the coaendpoint server.  After setting any
     * optional parameters, call the {@link ListCoa#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListCoa#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListCoa() {
      super(Coaendpoint.this, "GET", REST_PATH, null, com.sp.fanikiwa.entity.coaendpoint.model.CollectionResponseCoa.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCoa setAlt(java.lang.String alt) {
      return (ListCoa) super.setAlt(alt);
    }

    @Override
    public ListCoa setFields(java.lang.String fields) {
      return (ListCoa) super.setFields(fields);
    }

    @Override
    public ListCoa setKey(java.lang.String key) {
      return (ListCoa) super.setKey(key);
    }

    @Override
    public ListCoa setOauthToken(java.lang.String oauthToken) {
      return (ListCoa) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCoa setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCoa) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCoa setQuotaUser(java.lang.String quotaUser) {
      return (ListCoa) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCoa setUserIp(java.lang.String userIp) {
      return (ListCoa) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public ListCoa setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListCoa setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public ListCoa set(String parameterName, Object value) {
      return (ListCoa) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeCoa".
   *
   * This request holds the parameters needed by the coaendpoint server.  After setting any optional
   * parameters, call the {@link RemoveCoa#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveCoa removeCoa(java.lang.Long id) throws java.io.IOException {
    RemoveCoa result = new RemoveCoa(id);
    initialize(result);
    return result;
  }

  public class RemoveCoa extends CoaendpointRequest<Void> {

    private static final String REST_PATH = "coa/{id}";

    /**
     * Create a request for the method "removeCoa".
     *
     * This request holds the parameters needed by the the coaendpoint server.  After setting any
     * optional parameters, call the {@link RemoveCoa#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveCoa#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveCoa(java.lang.Long id) {
      super(Coaendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveCoa setAlt(java.lang.String alt) {
      return (RemoveCoa) super.setAlt(alt);
    }

    @Override
    public RemoveCoa setFields(java.lang.String fields) {
      return (RemoveCoa) super.setFields(fields);
    }

    @Override
    public RemoveCoa setKey(java.lang.String key) {
      return (RemoveCoa) super.setKey(key);
    }

    @Override
    public RemoveCoa setOauthToken(java.lang.String oauthToken) {
      return (RemoveCoa) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveCoa setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveCoa) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveCoa setQuotaUser(java.lang.String quotaUser) {
      return (RemoveCoa) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveCoa setUserIp(java.lang.String userIp) {
      return (RemoveCoa) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveCoa setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveCoa set(String parameterName, Object value) {
      return (RemoveCoa) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateCoa".
   *
   * This request holds the parameters needed by the coaendpoint server.  After setting any optional
   * parameters, call the {@link UpdateCoa#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.sp.fanikiwa.entity.coaendpoint.model.Coa}
   * @return the request
   */
  public UpdateCoa updateCoa(com.sp.fanikiwa.entity.coaendpoint.model.Coa content) throws java.io.IOException {
    UpdateCoa result = new UpdateCoa(content);
    initialize(result);
    return result;
  }

  public class UpdateCoa extends CoaendpointRequest<com.sp.fanikiwa.entity.coaendpoint.model.Coa> {

    private static final String REST_PATH = "coa";

    /**
     * Create a request for the method "updateCoa".
     *
     * This request holds the parameters needed by the the coaendpoint server.  After setting any
     * optional parameters, call the {@link UpdateCoa#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateCoa#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.sp.fanikiwa.entity.coaendpoint.model.Coa}
     * @since 1.13
     */
    protected UpdateCoa(com.sp.fanikiwa.entity.coaendpoint.model.Coa content) {
      super(Coaendpoint.this, "PUT", REST_PATH, content, com.sp.fanikiwa.entity.coaendpoint.model.Coa.class);
    }

    @Override
    public UpdateCoa setAlt(java.lang.String alt) {
      return (UpdateCoa) super.setAlt(alt);
    }

    @Override
    public UpdateCoa setFields(java.lang.String fields) {
      return (UpdateCoa) super.setFields(fields);
    }

    @Override
    public UpdateCoa setKey(java.lang.String key) {
      return (UpdateCoa) super.setKey(key);
    }

    @Override
    public UpdateCoa setOauthToken(java.lang.String oauthToken) {
      return (UpdateCoa) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateCoa setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateCoa) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateCoa setQuotaUser(java.lang.String quotaUser) {
      return (UpdateCoa) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateCoa setUserIp(java.lang.String userIp) {
      return (UpdateCoa) super.setUserIp(userIp);
    }

    @Override
    public UpdateCoa set(String parameterName, Object value) {
      return (UpdateCoa) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Coaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Coaendpoint}. */
    @Override
    public Coaendpoint build() {
      return new Coaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CoaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCoaendpointRequestInitializer(
        CoaendpointRequestInitializer coaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(coaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
